### ISSUE TITLE
GitHub Actions fail on forked repository

### ISSUE THREAD

**Issue by HiromuHota** [HazyResearch/fonduer#391]
**Describe the bug**

GitHub Actions fail on a forked repository because "Upload to coveralls.io" step fails.

**To Reproduce**
1. Fork HazyResearch/fonduer
2. Push any commit to your forked repository
3. GitHub Actions fails

**Expected behavior**

"Upload to coveralls.io" runs only on HazyResearch/fonduer

**Error Logs/Screenshots**

![image](https://user-images.githubusercontent.com/20668349/78952435-5a764f80-7a8a-11ea-8297-8dd0d9615202.png)

**Comment by SenWu** [comment]
Maybe this is useful: https://community.codecov.io/t/whitelist-github-action-servers-to-upload-without-a-token/491/19

**Comment by HiromuHota** [comment]
I think the following is more suitable.
https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsif

Like below.
```
steps:
    - name: Upload to coveralls.io
      if: github.repo = 'HazyResearch/fonduer'
      run: |
          coverage combine
          coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.coveralls_repo_token }}
```

I'll make a PR and submit.
